#ifndef GSP_CONSTANTS_H
#define GSP_CONSTANTS_H

enum {
    NODE_TYPE_PORT = 'P',
    NODE_TYPE_STATION_1 = 'S',
    NODE_TYPE_STATION_2 = 'T',
    NODE_TYPE_WAYPOINT = 'W',
    NODE_TYPE_BOAT = 'B'
};

enum {
    LOG_DEBUG = 0,
    LOG_INFO = 1,
    LOG_WARN = 2,
    LOG_ERROR = 3
};

enum {
    MIP_STATUS_OPTIMAL = 2,
    MIP_STATUS_SUBOPTIMAL = 9,
    MIP_STATUS_TIME_LIMIT = 9,
    MIP_STATUS_INFEASIBLE = 3
};

#define MAX_NODES 10000
#define MAX_STATIONS 5000
#define MAX_WAYPOINTS 1000
#define MAX_LOG_LINES 10000
#define MAX_TOUR_LENGTH 10000

#define DEFAULT_MIP_TIME_LIMIT 300
#define DEFAULT_L2SEG_MIN 60
#define DEFAULT_L2SEG_MAX 480
#define DEFAULT_L2SEG_STEP 60
#define DEFAULT_SEGMENT_STRIDE 30

#endif

