#ifndef GSP_DB_SCHEMA_H
#define GSP_DB_SCHEMA_H

/* Placeholder schema strings for SQLite tables. */

#define DB_SCHEMA_LOCATIONS "CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT, lat INTEGER, lon INTEGER, lat_decimal REAL, lon_decimal REAL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
#define DB_SCHEMA_PORTS "CREATE TABLE IF NOT EXISTS ports (id INTEGER PRIMARY KEY AUTOINCREMENT, location_id INTEGER, name TEXT, flag INTEGER);"
#define DB_SCHEMA_BOATS "CREATE TABLE IF NOT EXISTS boats (id INTEGER PRIMARY KEY AUTOINCREMENT, start_location_id INTEGER, end_location_id INTEGER, capacity INTEGER, c1 INTEGER, c2 INTEGER, c3 INTEGER, c4 INTEGER, c5 INTEGER, c6 INTEGER, name TEXT);"
#define DB_SCHEMA_STATS "CREATE TABLE IF NOT EXISTS stats (id INTEGER PRIMARY KEY AUTOINCREMENT, ext_id INTEGER, subid INTEGER, flag INTEGER, start_location_id INTEGER, end_location_id INTEGER, botndypi_kastad INTEGER, botndypi_hift INTEGER, remark TEXT);"
#define DB_SCHEMA_WAYPOINTS "CREATE TABLE IF NOT EXISTS waypoints (id INTEGER PRIMARY KEY AUTOINCREMENT, location_id INTEGER, flag INTEGER);"
#define DB_SCHEMA_METADATA "CREATE TABLE IF NOT EXISTS metadata (key TEXT PRIMARY KEY, value TEXT, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
#define DB_SCHEMA_SOLUTIONS "CREATE TABLE IF NOT EXISTS solutions (id INTEGER PRIMARY KEY AUTOINCREMENT, strategy TEXT, total_distance REAL, runtime_seconds REAL, payload TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
#define DB_SCHEMA_SWEEP_RUNS "CREATE TABLE IF NOT EXISTS sweep_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, l2seg INTEGER, iteration INTEGER, total_distance REAL, improvement REAL, elapsed_seconds REAL, payload TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"

#endif

